Update Plugin Version to ver.5 so that it matches Client Version
Current issue: 
Error: Failed to instantiate provider "sendmail" to obtain schema: Incompatible API version with plugin. Plugin version: 1, Client versions: [5]